[package]
name = "pack-prost"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Jonathan Barnoud"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost-types = "0.12.3"
