on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/local
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Get Openmm
        run: |
          wget https://github.com/openmm/openmm/archive/refs/tags/7.7.0.tar.gz -O openmm-7.7.0.tar.gz
          tar -xf openmm-7.7.0.tar.gz
      - name: install OpenMM
        run: |
          echo $LD_LIBRARY_PATH
          cd openmm-7.7.0
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=$HOME/local \
            -DOPENMM_BUILD_OPENCL_LIB=OFF \
            -DOPENMM_BUILD_AMOEBA_PLUGIN=OFF \
            -DOPENMM_BUILD_DRUDE_PLUGIN=OFF \
            -DOPENMM_BUILD_PYTHON_WRAPPERS=OFF \
            -DOPENMM_BUILD_RPMD_PLUGIN=OFF \
          && make && make install
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          LD_LIBRARY_PATH: /home/runner/local/lib/
          OPENMM_HOME: /home/runner/local/